### PR TITLE
Save html

### LINKED ISSUE #8: Save html
Expose a new function that allows to save a dom element to a file.

`saveHtml(domElement, options)`

options:
- error: default value: `(e) => (alert(e.toString())`
- filename

### PR DESCRIPTION
**Pull request by wadjih-bencheikh18**
closes : https://github.com/zakodium-oss/dom-to-html/issues/8

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -1,89 +1 @@
...
-      canvas.height = height;
-      const ctx = canvas.getContext('2d') as CanvasRenderingContext2D;
-      ctx.drawImage(img, 0, 0, width, height);
-      callback(canvasToHtml(canvas));
-      resolve();
-    };
-    image.src = img.src;
-  });
-}
+export * from './domToHtml';
```
Comment (lpatiny) [inline src/index.ts:1]: You should also expose saveHtml

Comment (wadjih-bencheikh18) [reply src/index.ts:1]: fixed thank you
